wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.0
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1696693755.836767
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 49
      - 55
      - 71
      - 83
      2:
      - 1
      - 2
      - 3
      - 11
      - 49
      - 55
      - 71
      - 83
      3:
      - 23
      4: 3.10.6
      5: 0.15.0
      6: 4.30.2
      8:
      - 1
      - 3
      - 5
logdir:
  desc: null
  value: logs
mixed_precision:
  desc: null
  value: fp16
num_checkpoint_limit:
  desc: null
  value: 5
num_epochs:
  desc: null
  value: 100
per_prompt_stat_tracking:
  desc: null
  value:
    buffer_size: 16
    min_count: 16
resume_from:
  desc: null
  value: ''
run_name:
  desc: null
  value: ''
sample:
  desc: null
  value:
    batch_size: 1
    eta: 1.0
    guidance_scale: 7.5
    num_batches_per_epoch: 2
    num_steps: 20
save_freq:
  desc: null
  value: 20
seed:
  desc: null
  value: 42
train:
  desc: null
  value:
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_epsilon: 1.0e-08
    adam_weight_decay: 0.0001
    adv_clip_max: 5
    batch_size: 1
    cfg: true
    clip_range: 0.0001
    gradient_accumulation_steps: 1
    learning_rate: 0.0003
    max_grad_norm: 1.0
    num_inner_epochs: 1
    timestep_fraction: 1.0
    use_8bit_adam: false
use_lora:
  desc: null
  value: true
